INSERT INTO Restaurant (restaurant_name, location, restaurant_phone, email) VALUES ('Crust', 'Alpharetta', '6789777023', 'monopoly@fcc.com');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Chicken',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Pepperoni',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Special Sauce',5000,'Packet');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Sauce',5000,'Tsp');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Sausage',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Cheese',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Dough',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Flour',300,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Chocolate Chip',5000,'Packet');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Butter',5000,'Tsp');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Sugar',5000,'Tsp');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Eggs',5000,'Piece');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Hot Sauce',5000,'Tsp');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Garlic',5000,'Tsp');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Coke',5000,'Oz');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','BBQ Sauce',5000,'Tsp');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Onion',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Green Pepper',500,'Lb');
INSERT INTO Inventory (restaurant_name, ingredient_name, quantity, unit) VALUES ('Crust','Jalapeno',500,'Lb');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Veggie Pizza',15);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Veggie Pizza','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Veggie Pizza','Onion',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Veggie Pizza','Cheese',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Veggie Pizza','Sauce',6,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Veggie Pizza','Jalapeno',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Veggie Pizza','Green Pepper',.5,'Lb');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Cheese Pizza',10);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Cheese Pizza','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Cheese Pizza','Special Sauce',1,'Packet');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Cheese Pizza','Cheese',.8,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Cheese Pizza','Sauce',6,'Tsp');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Meat Lover Pizza',15);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Meat Lover Pizza','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Meat Lover Pizza','Sausage',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Meat Lover Pizza','Cheese',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Meat Lover Pizza','Sauce',6,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Meat Lover Pizza','Chicken',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Meat Lover Pizza','Pepperoni',.5,'Lb');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','BBQ Chicken Pizza',12);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','BBQ Chicken Pizza','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','BBQ Chicken Pizza','BBQ Sauce',1,'Packet');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','BBQ Chicken Pizza','Cheese',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','BBQ Chicken Pizza','Sauce',6,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','BBQ Chicken Pizza','Chicken',.5,'Lb');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Pepperoni Pizza',12);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Pepperoni Pizza','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Pepperoni Pizza','Special Sauce',1,'Packet');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Pepperoni Pizza','Cheese',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Pepperoni Pizza','Sauce',6,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Pepperoni Pizza','Pepperoni',.5,'Lb');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Bread Sticks',5);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Bread Sticks','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Bread Sticks','Butter',4,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Bread Sticks','Special Sauce',1,'Packet');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Bread Sticks','Sauce',6,'Tsp');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Garlic Knots',5);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Garlic Knots','Dough',1,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Garlic Knots','Butter',4,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Garlic Knots','Sauce',4,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Garlic Knots','Garlic',4,'Tsp');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Drink',2);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Drink','Coke',22,'Oz');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Wings',8);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Wings','Hot Sauce',4,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Wings','Chicken',2,'Lb');
INSERT INTO Menu (restaurant_name,item_name,price) VALUES ('Crust','Brownies',5);
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Brownies','Butter',4,'Tsp');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Brownies','Chocolate Chip',1,'Packet');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Brownies','Eggs',2,'Piece');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Brownies','Flour',.5,'Lb');
INSERT INTO Ingredient (restaurant_name,item_name,ingredient_name,portion,unit) VALUES ('Crust','Brownies','Sugar',4,'Tsp');
